name: mem_plus_plus
description: Memory improvement app.

version: 2.2.4+48

environment:
  sdk: ">2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2 
  shared_preferences: ^2.0.5
  # transformer_page_view: ^0.1.6
  csv: ^5.0.0
  # pimp_my_button: ^1.0.0
  # edit_distance: ^0.4.1
  auto_size_text: ^3.0.0
  shimmer: ^3.0.0
  flutter_local_notifications: ^5.0.0
  rxdart: ^0.26.0
  path_provider: ^2.0.1
  flip_card: ^0.5.0
  flutter_datetime_picker: ^1.5.0
  material_design_icons_flutter: ^7.0.7296
  url_launcher: ^6.0.3
  # random_words: ^1.0.2
  # password: ^1.0.0
  flutter_native_timezone: ^1.0.10
  # simple_animations: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_automation:
  flutter_launcher_icons: ^0.13.1
  # flutter_launcher_icons:
  #   git:
  #     url: https://github.com/knyghtryda/flutter_launcher_icons
  #     ref: scaling

flutter_icons:
  ios: true
  android: true
  image_path: "assets/launcher/mempp_combined.png"
  adaptive_icon_background: "assets/launcher/mempp_back_white.png"
  adaptive_icon_foreground: "assets/launcher/mempp_brain.png"
  # image_path: "assets/launcher/icon.png"
  # adaptive_icon_foreground_scale_factor: 0.66

flutter:
  uses-material-design: true
  fonts:
    - family: Rajdhani
      fonts:
        - asset: assets/fonts/Rajdhani-Regular.ttf
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand.ttf
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa.ttf
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
    - family: SpaceMono
      fonts:
        - asset: assets/fonts/SpaceMono-Regular.ttf
    - family: Viga
      fonts:
        - asset: assets/fonts/Viga-Regular.ttf
    - family: CabinSketch
      fonts:
        - asset: assets/fonts/CabinSketch-Regular.ttf
    - family: JockeyOne
      fonts:
        - asset: assets/fonts/JockeyOne-Regular.ttf
  assets:
    - assets/images/
    - assets/images/men/
    - assets/images/women/