import 'package:flutter/material.dart';
import 'package:material_design_icons_flutter/material_design_icons_flutter.dart';

// debug mode - FALSE for production
const bool debugModeEnabled = true;
const int debugTestTime = 5;

const String usernameKey = 'Username';

// dark mode colors
Color darkBackgroundColorPermanent = Colors.grey[800]!;
Color darkBackgroundHighlightColorPermanent = Colors.white;
Color darkBackgroundSemiColorPermanent = Colors.grey[600]!;
Color darkBackgroundSemiHighlightColorPermanent = Colors.grey[200]!;
Color lightBackgroundColorPermanent = Colors.white;
Color lightBackgroundHighlightColorPermanent = Colors.black;
Color lightBackgroundSemiColorPermanent = Colors.grey[400]!;
Color lightBackgroundSemiHighlightColorPermanent = Colors.grey[600]!;
Color backgroundColor = darkBackgroundColorPermanent;
Color backgroundSemiColor = darkBackgroundSemiColorPermanent;
Color backgroundHighlightColor = darkBackgroundHighlightColorPermanent;
Color backgroundSemiHighlightColor = darkBackgroundSemiHighlightColorPermanent;
const String darkModeKey = 'DarkMode';
const String darkModeNotificationFirstTimeKey = 'DarkModeNotificationFirstTime';

// general
const String welcomeKey = 'Welcome';
const String homepageFirstHelpKey = 'HomepageFirstHelp';
const String homepageKey = 'Homepage';
const String firstTimeAppKey = 'FirstTimeApp';
const String activityStatesKey = 'ActivityStates';

// notifications
const String dailyReminderKey = 'Daily Reminder';
const String dailyReminderIdKey = '1';
const String testReminderKey = 'Test Reminder';
const String testReminderIdKey = '2';

// Single Digit
const String singleDigitKey = 'SingleDigit';
const String singleDigitEditKey = 'SingleDigitEdit';
const String singleDigitPracticeKey = 'SingleDigitPractice';
const String singleDigitMultipleChoiceTestKey = 'SingleDigitMultipleChoice';
const String singleDigitTimedTestPrepKey = 'SingleDigitTimedTestPrep';
const String singleDigitTimedTestKey = 'SingleDigitTimedTest';
const String singleDigitTestActiveKey = 'SingleDigitTimedTestActive';
const String singleDigitEditFirstHelpKey = 'SingleDigitEditFirstHelp';
const String singleDigitPracticeFirstHelpKey = 'SingleDigitPracticeFirstHelp';
const String singleDigitMultipleChoiceTestFirstHelpKey =
    'SingleDigitMultipleChoiceTestFirstHelp';
const String singleDigitTimedTestPrepFirstHelpKey =
    'SingleDigitTimedTestPrepFirstHelp';
const String singleDigitTimedTestFirstHelpKey = 'SingleDigitTimedTestFirstHelp';
const String singleDigitTimedTestCompleteKey = 'SingleDigitTimedTestComplete';

// lesson 1
const String lesson1Key = 'Lesson1';
const String lesson1CompleteKey = 'Lesson1Complete';

// faces easy
const String faceTimedTestPrepKey = 'FaceTimedTestPrep';
const String faceTimedTestKey = 'FaceTimedTest';
const String faceTestActiveKey = 'FaceTestActive';
const String faceTimedTestPrepFirstHelpKey = 'FaceTimedTestPrepFirstHelp';
const String faceTimedTestFirstHelpKey = 'FaceTimedTestFirstHelp';
const String faceTimedTestCompleteKey = 'FaceTimedTestComplete';

// planet
const String planetTimedTestPrepKey = 'PlanetTimedTestPrep';
const String planetTimedTestKey = 'PlanetTimedTest';
const String planetTestActiveKey = 'PlanetTestActive';
const String planetTimedTestPrepFirstHelpKey = 'PlanetTimedTestPrepFirstHelp';
const String planetTimedTestFirstHelpKey = 'PlanetTimedTestFirstHelp';
const String planetTimedTestCompleteKey = 'PlanetTimedTestComplete';

// Alphabet
const String alphabetKey = 'Alphabet';
const String alphabetEditKey = 'AlphabetEdit';
const String alphabetPracticeKey = 'AlphabetPractice';
const String alphabetWrittenTestKey = 'AlphabetWrittenTest';
const String alphabetTimedTestPrepKey = 'AlphabetTimedTestPrep';
const String alphabetTimedTestKey = 'AlphabetTimedTest';
const String alphabetTestActiveKey = 'AlphabetTestActive';
const String alphabetEditFirstHelpKey = 'AlphabetEditFirstHelp';
const String alphabetPracticeFirstHelpKey = 'AlphabetPracticeFirstHelp';
const String alphabetWrittenTestFirstHelpKey =
    'AlphabetMultipleChoiceTestFirstHelp';
const String alphabetTimedTestPrepFirstHelpKey =
    'AlphabetTimedTestPrepFirstHelp';
const String alphabetTimedTestFirstHelpKey = 'AlphabetTimedTestFirstHelp';
const String alphabetTimedTestCompleteKey = 'AlphabetTimedTestComplete';

// lesson 2
const String lesson2Key = 'Lesson2';
const String lesson2CompleteKey = 'Lesson2Complete';

// airport
const String airportTimedTestPrepKey = 'AirportTimedTestPrep';
const String airportTimedTestKey = 'AirportTimedTest';
const String airportTestActiveKey = 'AirportTestActive';
const String airportTimedTestPrepFirstHelpKey = 'AirportTimedTestPrepFirstHelp';
const String airportTimedTestFirstHelpKey = 'AirportTimedTestFirstHelp';
const String airportTimedTestCompleteKey = 'AirportTimedTestComplete';

// phonetic alphabet
const String phoneticAlphabetTimedTestPrepKey = 'PhoneticAlphabetTimedTestPrep';
const String phoneticAlphabetTimedTestKey = 'PhoneticAlphabetTimedTest';
const String phoneticAlphabetTestActiveKey = 'PhoneticAlphabetTestActive';
const String phoneticAlphabetTimedTestPrepFirstHelpKey =
    'PhoneticAlphabetTimedTestPrepFirstHelp';
const String phoneticAlphabetTimedTestFirstHelpKey =
    'PhoneticAlphabetTimedTestFirstHelp';
const String phoneticAlphabetTimedTestCompleteKey =
    'PhoneticAlphabetTimedTestComplete';

// PAO
const String paoKey = 'PAO';
const String paoEditKey = 'PAOEdit';
const String paoPracticeKey = 'PAOPractice';
const String paoMultipleChoiceTestKey = 'PAOMultipleChoice';
const String paoTimedTestPrepKey = 'PAOTimedTestPrep';
const String paoTimedTestKey = 'PAOTimedTest';
const String paoTestActiveKey = 'PAOTestActive';
const String paoEditFirstHelpKey = 'PAOEditFirstHelp';
const String paoPracticeFirstHelpKey = 'PAOPracticeFirstHelp';
const String paoMultipleChoiceTestFirstHelpKey =
    'PAOMultipleChoiceTestFirstHelp';
const String paoTimedTestPrepFirstHelpKey = 'PAOTimedTestPrepFirstHelp';
const String paoTimedTestFirstHelpKey = 'PAOTimedTestFirstHelp';
const String paoTimedTestCompleteKey = 'PAOTimedTestComplete';

// lesson 3
const String lesson3Key = 'Lesson3';
const String lesson3CompleteKey = 'Lesson3Complete';

// faces difficult
const String face2TimedTestPrepKey = 'Face2TimedTestPrep';
const String face2TimedTestKey = 'Face2TimedTest';
const String face2TestActiveKey = 'Face2TestActive';
const String face2TimedTestPrepFirstHelpKey = 'Face2TimedTestPrepFirstHelp';
const String face2TimedTestFirstHelpKey = 'Face2TimedTestFirstHelp';
const String face2TimedTestCompleteKey = 'Face2TimedTestComplete';

// pi
const String piTimedTestPrepKey = 'PiTimedTestPrep';
const String piTimedTestKey = 'PiTimedTest';
const String piTestActiveKey = 'PiTestActive';
const String piTimedTestPrepFirstHelpKey = 'PiTimedTestPrepFirstHelp';
const String piTimedTestFirstHelpKey = 'PiTimedTestFirstHelp';
const String piTimedTestCompleteKey = 'PiTimedTestComplete';

// games
const String gamesAvailableKey = 'GamesAvailable';
const String newGamesAvailableKey = 'NewGamesAvailable';
const String gamesFirstHelpKey = 'GamesFirstHelp';
const String fadeGameAvailableKey = 'FadeGameAvailable';
const String fadeGameFirstHelpKey = 'FadeGameFirstHelp';
const String fadeGameFirstViewKey = 'FadeGameFirstView';
const String morseGameAvailableKey = 'MorseGameAvailable';
const String morseGameFirstHelpKey = 'MorseGameFirstHelp';
const String morseGameFirstViewKey = 'MorseGameFirstView';
const String irrationalGameAvailableKey = 'IrrationalGameAvailable';
const String irrationalGameFirstHelpKey = 'IrrationalGameFirstHelp';
const String irrationalGameFirstViewKey = 'IrrationalGameFirstView';
const String triviaGameAvailableKey = 'TriviaGameAvailable';
const String triviaGameFirstViewKey = 'TriviaGameFirstView';
const String presidentsTriviaGameFirstHelpKey = 'PresidentsTriviaGameFirstHelp';
const String elementsTriviaGameFirstHelpKey = 'ElementsTriviaGameFirstHelp';
const String countriesTriviaGameFirstHelpKey = 'CountriesTriviaGameFirstHelp';

// custom memory
const String customMemoriesKey = 'CustomMemories';
const String customMemoryManagerAvailableKey = 'CustomMemoryManagerAvailable';
const String shortTerm = 'short term (1d ~ 1w)';
const String mediumTerm = 'medium term (1w ~ 3m)';
const String longTerm = 'long term (3m ~ 1y)';
const String extraLongTerm = 'extra long term (1y ~ life)';
const String contactString = 'Contact';
const String idCardString = 'ID/Credit Card';
const String otherString = 'Other';
const String customMemoryManagerFirstHelpKey = 'CustomMemoryManagerFirstHelp';
const String customMemoryTestFirstHelpKey = 'CustomMemoryTestFirstHelp';

// Deck
const String deckKey = 'Deck';
const String deckEditKey = 'DeckEdit';
const String deckPracticeKey = 'DeckPractice';
const String deckMultipleChoiceTestKey = 'DeckMultipleChoice';
const String deckTimedTestPrepKey = 'DeckTimedTestPrep';
const String deckTimedTestKey = 'DeckTimedTest';
const String deckTestActiveKey = 'DeckTestActive';
const String deckEditFirstHelpKey = 'DeckEditFirstHelp';
const String deckPracticeFirstHelpKey = 'DeckPracticeFirstHelp';
const String deckMultipleChoiceTestFirstHelpKey =
    'DeckMultipleChoiceTestFirstHelp';
const String deckTimedTestPrepFirstHelpKey = 'DeckTimedTestPrepFirstHelp';
const String deckTimedTestFirstHelpKey = 'DeckTimedTestFirstHelp';
const String deckTimedTestCompleteKey = 'DeckTimedTestComplete';

// Triple Digit
const String tripleDigitKey = 'TripleDigit';
const String tripleDigitEditKey = 'TripleDigitEdit';
const String tripleDigitPracticeKey = 'TripleDigitPractice';
const String tripleDigitMultipleChoiceTestKey = 'TripleDigitMultipleChoice';
const String tripleDigitTimedTestPrepKey = 'TripleDigitTimedTestPrep';
const String tripleDigitTimedTestKey = 'TripleDigitTimedTest';
const String tripleDigitTestActiveKey = 'TripleDigitTimedTestActive';
const String tripleDigitEditFirstHelpKey = 'TripleDigitEditFirstHelp';
const String tripleDigitPracticeFirstHelpKey = 'TripleDigitPracticeFirstHelp';
const String tripleDigitMultipleChoiceTestFirstHelpKey =
    'TripleDigitMultipleChoiceTestFirstHelp';
const String tripleDigitTimedTestPrepFirstHelpKey =
    'TripleDigitTimedTestPrepFirstHelp';
const String tripleDigitTimedTestFirstHelpKey = 'TripleDigitTimedTestFirstHelp';
const String tripleDigitTimedTestCompleteKey = 'TripleDigitTimedTestComplete';

var editIcon = Icon(Icons.edit);
var practiceIcon = Icon(Icons.flip);
var multipleChoiceTestIcon = Icon(Icons.list);
var timedTestPrepIcon = Icon(Icons.add_alarm);
var timedTestIcon = Icon(Icons.access_alarm);
var writtenTestIcon = Icon(Icons.text_format);
var lessonIcon = Icon(MdiIcons.brain);
var planetIcon = Icon(MdiIcons.earth);
var faceIcon = Icon(MdiIcons.faceMan);
var face2Icon = Icon(MdiIcons.faceRecognition);
var piIcon = Icon(MdiIcons.pi);
var airportIcon = Icon(MdiIcons.airplaneTakeoff);
var phoneticIcon = Icon(MdiIcons.sortAlphabeticalAscending);

Map termDurationsMap = {
  shortTerm: debugModeEnabled
      ? [
          Duration(seconds: 1),
          Duration(seconds: 3),
          Duration(seconds: 5),
          Duration(seconds: 8),
          Duration(seconds: 1)
        ]
      : [
          Duration(minutes: 20),
          Duration(minutes: 80),
          Duration(minutes: 220),
          Duration(minutes: 540),
          Duration(minutes: 1240)
        ],
  mediumTerm: [
    Duration(minutes: 30),
    Duration(hours: 3),
    Duration(hours: 12),
    Duration(days: 2),
    Duration(days: 10)
  ],
  longTerm: [
    Duration(minutes: 30),
    Duration(hours: 3),
    Duration(hours: 12),
    Duration(days: 2),
    Duration(days: 10),
    Duration(days: 30),
    Duration(days: 90)
  ],
  extraLongTerm: debugModeEnabled
      ? [
          Duration(days: 4),
          Duration(days: 4),
          Duration(seconds: 5),
          Duration(seconds: 8),
          Duration(seconds: 1)
        ]
      : [
          Duration(minutes: 30),
          Duration(hours: 3),
          Duration(hours: 12),
          Duration(days: 2),
          Duration(days: 10),
          Duration(days: 30),
          Duration(days: 90),
          Duration(days: 180),
          Duration(days: 400)
        ],
};

Map customMemoryIconMap = {
  contactString: Icons.person_pin,
  idCardString: Icons.credit_card,
  otherString: Icons.add,
};

Map morseQuiz = {
  'most common red fruit': 'apple',
  'you pedal it has two wheels': 'bicycle',
  'you sit down on it has four legs': 'chair',
  'four letter eating utensil': 'fork',
  'day before tomorrow': 'today',
  'you make calls on it': 'phone',
  'furniture that you sleep on': 'bed',
  'biggest of five on hand': 'thumb',
  'wax and wick burned for light': 'candle',
  'small bright objects in the sky': 'starts',
  'containing nothing': 'empty',
  'leather around the waist': 'belt',
  'comes out of the tap': 'water',
  'opposite of long': 'short',
  'color of coffee': 'brown',
  'worn on the finger': 'ring',
  'easier way to say incorrect': 'wrong',
  'hard shell baby bird inside': 'egg',
  'horse with black and white stripes': 'zebra',
  'water from the sky': 'rain',
  'thousands grow out of your head': 'hair',
  'three hundred sixty five days': 'year',
  'sixty minutes is an': 'hour',
  'most popular stringed instrument': 'guitar',
  'the tallest animal': 'giraffe',
  'runs in our veins': 'blood',
  'sandy area along the shore': 'beach',
  'large fabric rectangle on the floor': 'carpet',
  'biggest planet in our solar system': 'jupiter',
  'sudoku is a type of': 'puzzle',
  'stop with intent to continue later': 'pause',
  'erupts with lava': 'volcano',
  'unwanted emails': 'spam',
  'show something that was hidden': 'reveal',
  'organ that pumps blood': 'heart',
  'a hundred years': 'century',
  'where you type on computers': 'keyboard',
  'tons of sand and maybe an oasis': 'desert',
  'wacky scene when sleeping': 'dream',
  'connects ground to ceiling': 'wall',
  'color of banana': 'yellow',
  'color of snow': 'white',
  'color of grass': 'green',
  'lead writing utensil': 'pencil',
};

List letters = [
  'A',
  'B',
  'C',
  'D',
  'E',
  'F',
  'G',
  'H',
  'I',
  'J',
  'K',
  'L',
  'M',
  'N',
  'O',
  'P',
  'Q',
  'R',
  'S',
  'T',
  'U',
  'V',
  'W',
  'X',
  'Y',
  'Z'
];
List phoneticAlphabet = [
  'Alpha',
  'Bravo',
  'Charlie',
  'Delta',
  'Echo',
  'Foxtrot',
  'Golf',
  'Hotel',
  'India',
  'Juliett',
  'Kilo',
  'Lima',
  'Mike',
  'November',
  'Oscar',
  'Papa',
  'Quebec',
  'Romeo',
  'Sierra',
  'Tango',
  'Uniform',
  'Victor',
  'Whiskey',
  'X-ray',
  'Yankee',
  'Zulu',
];
List morse = [
  '•-',
  '-•••',
  '-•-•',
  '-••',
  '•',
  '••-•',
  '--•',
  '••••',
  '••',
  '•---',
  '-•-',
  '•-••',
  '--',
  '-•',
  '---',
  '•--•',
  '--•-',
  '•-•',
  '•••',
  '-',
  '••-',
  '•••-',
  '•--',
  '-••-',
  '-•--',
  '--••',
];

List<String> jobs = [
  'Flight Attendant',
  'Engineer',
  'Coder',
  'Nurse',
  'Lawyer',
  'Doctor',
  'Photographer',
  'Project Manager',
  'Teacher',
  'Real Estate Agent',
  'Chef',
  'Sales',
  'Marketing',
  'CEO',
  'Athelete',
  'Journalist',
  'Dentist',
  'Receptionist',
];

List<String> cities = [
  'New York',
  'Los Angeles',
  'Chicago',
  'Houston',
  'Phoenix',
  'Philadelphia',
  'San Antonio',
  'San Diego',
  'Dallas',
  'San Jose',
  'Austin',
  'Jacksonville',
  'Fort Worth',
  'Columbus',
  'San Francisco',
  'Charlotte',
  'Seattle',
  'Denver',
  'Boston',
  'Detroit',
  'Nashville',
  'Portland',
  'Las Vegas',
  'Atlanta',
  'Miami',
  'New Orleans',
  'Honolulu',
  'St Louis',
];

List singleDigitSuggestions = [
  'hero  /  ball, gumball, marble',
  'bun  /  baseball bat, pencil',
  'shoe  /  swan, duck, goose',
  'tree  /  bra, boxers, bathing suit',
  'door  /  sailboat, yacht, boat',
  'hive  /  snake, worm, turtle',
  'sticks  /  golf club, tennis racket',
  'heaven  /  boomerang, arrowhead',
  'gate  /  snowman, reindeer',
  'wine  /  flagpole, balloon',
];

List alphabetSuggestions = [
  'apple, archer, axe',
  'bicycle, bank, barbarian',
  'cat, chimpanzee, Christmas',
  'dinosaur, dealership, dock',
  'elephant, eclipse, egg',
  'flamingo, fang, fedora',
  'godzilla, ghost, globe',
  'honey, heaven, highway',
  'igloo, iguana, iceberg',
  'jar, jaguar, Jamaica',
  'kangaroo, keg, ketchup',
  'lava, laser, leg',
  'mountain, magazine, mailbox',
  'ninja, nachos, noodle',
  'ocarina, octagon, onion',
  'piano, peacock, pub',
  'quicksand, quadriceps, quail',
  'root, rattle, railroad',
  'skeleton, sack, saw',
  'tattoo, tampon, tablet',
  'umbrella, ukulele, university',
  'violin, vacuum, valley',
  'wagon, wand, waterfall',
  'xylophone, x-ray, xerox',
  'yak, yardstick, yurt',
  'zipper, zoo, zapper',
];

String piValue = '3.14159265358979323846264338327950288419716939937510'
    '58209749445923078164062862089986280348253421170679'
    '82148086513282306647093844609550582231725359408128'
    '48111745028410270193852110555964462294895493038196'
    '44288109756659334461284756482337867831652712019091'
    '45648566923460348610454326648213393607260249141273'
    '72458700660631558817488152092096282925409171536436'
    '78925903600113305305488204665213841469519415116094'
    '33057270365759591953092186117381932611793105118548'
    '07446237996274956735188575272489122793818301194912'
    '98336733624406566430860213949463952247371907021798'
    '60943702770539217176293176752384674818467669405132'
    '00056812714526356082778577134275778960917363717872'
    '14684409012249534301465495853710507922796892589235'
    '42019956112129021960864034418159813629774771309960'
    '51870721134999999837297804995105973173281609631859'
    '50244594553469083026425223082533446850352619311881'
    '71010003137838752886587533208381420617177669147303'
    '59825349042875546873115956286388235378759375195778'
    '18577805321712268066130019278766111959092164201989';

String eValue =
    '2.71828182845904523536028747135266249775724709369995957496696762772407663035354759457138217852516642742746639193200305'
    '99218174135966290435729003342952605956307381323286279434907632338298807531952510190115738341879307021540891499348841675092447614606680'
    '82264800168477411853742345442437107539077744992069551702761838606261331384583000752044933826560297606737113200709328709127443747047230'
    '69697720931014169283681902551510865746377211125238978442505695369677078544996996794686445490598793163688923009879312773617821542499922'
    '95763514822082698951936680331825288693984964651058209392398294887933203625094431173012381970684161403970198376793206832823764648042953'
    '11802328782509819455815301756717361332069811250996181881593041690351598888519345807273866738589422879228499892086805825749279610484198'
    '44436346324496848756023362482704197862320900216099023530436994184914631409343173814364054625315209618369088870701676839642437814059271'
    '45635490613031072085103837505101157477041718986106873969655212671546889570350354';

Map presidents = {
  'washington': {'name': 'George Washington', 'firstYear': 1789},
  'adams': {'name': 'John Adams', 'firstYear': 1797},
  'jefferson': {'name': 'Thomas Jefferson', 'firstYear': 1801},
  'madison': {'name': 'James Madison', 'firstYear': 1809},
  'monroe': {'name': 'James Monroe', 'firstYear': 1817},
  'adams2': {'name': 'John Quency Adams', 'firstYear': 1825},
  'jackson': {'name': 'Andrew Jackson', 'firstYear': 1829},
  'buren': {'name': 'Martin Van Buren', 'firstYear': 1837},
  'harrison': {'name': 'William Henry Harrison', 'firstYear': 1841},
  'tyler': {'name': 'John Tyler', 'firstYear': 1841},
  'polk': {'name': 'James K. Polk', 'firstYear': 1845},
  'taylor': {'name': 'Zachary Taylor', 'firstYear': 1849},
  'fillmore': {'name': 'Millard Fillmore', 'firstYear': 1850},
  'pierce': {'name': 'Fraklin Pierce', 'firstYear': 1853},
  'buchanan': {'name': 'James Buchanan', 'firstYear': 1857},
  'lincoln': {'name': 'Abraham Lincoln', 'firstYear': 1861},
  'johnson': {'name': 'Andrew Johnson', 'firstYear': 1865},
  'grant': {'name': 'Ulysses S. Grant', 'firstYear': 1869},
  'hayes': {'name': 'Rutherford B. Hayes', 'firstYear': 1877},
  'garfield': {'name': 'James A. Garfield', 'firstYear': 1881},
  'arthur': {'name': 'Chester A. Authur', 'firstYear': 1881},
  'cleveland': {'name': 'Grover Cleveland', 'firstYear': 1885},
  'harrison2': {'name': 'Benjamin Harrison', 'firstYear': 1889},
  'cleveland2': {'name': 'Grover Cleveland (second term)', 'firstYear': 1893},
  'mckinley': {'name': 'William McKinley', 'firstYear': 1897},
  'roosevelt': {'name': 'Theodore Roosevelt', 'firstYear': 1901},
  'taft': {'name': 'William Howard Taft', 'firstYear': 1909},
  'wilson': {'name': 'Woodrow Wilson', 'firstYear': 1913},
  'harding': {'name': 'Warren G. Harding', 'firstYear': 1921},
  'coolidge': {'name': 'Calvin Coolidge', 'firstYear': 1923},
  'hoover': {'name': 'Herbert Hoover', 'firstYear': 1929},
  'roosevelt2': {'name': 'Franklin D. Roosevelt', 'firstYear': 1933},
  'truman': {'name': 'Harry S. Truman', 'firstYear': 1945},
  'eisenhower': {'name': 'Dwight D. Eisenhower', 'firstYear': 1953},
  'kennedy': {'name': 'John F. Kennedy', 'firstYear': 1961},
  'johnson2': {'name': 'Lyndon B. Johnson', 'firstYear': 1963},
  'nixon': {'name': 'Richard Nixon', 'firstYear': 1969},
  'ford': {'name': 'Gerald Ford', 'firstYear': 1974},
  'carter': {'name': 'Jimmy Carter', 'firstYear': 1977},
  'reagan': {'name': 'Ronald Reagan', 'firstYear': 1981},
  'bush': {'name': 'George H. W. Bush', 'firstYear': 1989},
  'clinton': {'name': 'Bill Clinton', 'firstYear': 1993},
  'bush2': {'name': 'George W. Bush', 'firstYear': 2001},
  'obama': {'name': 'Barack Obama', 'firstYear': 2009},
  'trump': {'name': 'Donald Trump', 'firstYear': 2017},
};

Map elements = {
  '1': {'name': 'Hydrogen', 'atomicWeight': 1.008, 'symbol': 'H'},
  '2': {'name': 'Helium', 'atomicWeight': 4.0026, 'symbol': 'He'},
  '3': {'name': 'Lithium', 'atomicWeight': 6.94, 'symbol': 'Li'},
  '4': {'name': 'Beryllium', 'atomicWeight': 9.0122, 'symbol': 'Be'},
  '5': {'name': 'Boron', 'atomicWeight': 10.81, 'symbol': 'B'},
  '6': {'name': 'Carbon', 'atomicWeight': 12.011, 'symbol': 'C'},
  '7': {'name': 'Nitrogen', 'atomicWeight': 14.007, 'symbol': 'N'},
  '8': {'name': 'Oxygen', 'atomicWeight': 15.999, 'symbol': 'O'},
  '9': {'name': 'Fluorine', 'atomicWeight': 18.998, 'symbol': 'F'},
  '10': {'name': 'Neon', 'atomicWeight': 20.180, 'symbol': 'Ne'},
  '11': {'name': 'Sodium', 'atomicWeight': 22.990, 'symbol': 'Na'},
  '12': {'name': 'Magnesium', 'atomicWeight': 24.305, 'symbol': 'Mg'},
  '13': {'name': 'Aluminium', 'atomicWeight': 26.982, 'symbol': 'Al'},
  '14': {'name': 'Silicon', 'atomicWeight': 28.085, 'symbol': 'Si'},
  '15': {'name': 'Phosphorus', 'atomicWeight': 30.974, 'symbol': 'P'},
  '16': {'name': 'Sulfur', 'atomicWeight': 32.06, 'symbol': 'S'},
  '17': {'name': 'Chlorine', 'atomicWeight': 35.45, 'symbol': 'Cl'},
  '18': {'name': 'Argon', 'atomicWeight': 39.948, 'symbol': 'Ar'},
  '19': {'name': 'Potassium', 'atomicWeight': 39.098, 'symbol': 'K'},
  '20': {'name': 'Calcium', 'atomicWeight': 40.078, 'symbol': 'Ca'},
  '21': {'name': 'Scandium', 'atomicWeight': 44.956, 'symbol': 'Sc'},
  '22': {'name': 'Titanium', 'atomicWeight': 47.876, 'symbol': 'Ti'},
  '23': {'name': 'Vanadium', 'atomicWeight': 50.942, 'symbol': 'V'},
  '24': {'name': 'Chromium', 'atomicWeight': 51.996, 'symbol': 'Cr'},
  '25': {'name': 'Manganese', 'atomicWeight': 54.938, 'symbol': 'Mn'},
  '26': {'name': 'Iron', 'atomicWeight': 55.845, 'symbol': 'Fe'},
  '27': {'name': 'Cobalt', 'atomicWeight': 58.933, 'symbol': 'Co'},
  '28': {'name': 'Nickel', 'atomicWeight': 58.693, 'symbol': 'Ni'},
  '29': {'name': 'Copper', 'atomicWeight': 63.546, 'symbol': 'Cu'},
  '30': {'name': 'Zinc', 'atomicWeight': 65.38, 'symbol': 'Zn'},
  '31': {'name': 'Gallium', 'atomicWeight': 69.723, 'symbol': 'Ga'},
  '32': {'name': 'Germanium', 'atomicWeight': 72.630, 'symbol': 'Ge'},
  '33': {'name': 'Arsenic', 'atomicWeight': 74.922, 'symbol': 'As'},
  '34': {'name': 'Selenium', 'atomicWeight': 78.971, 'symbol': 'Se'},
  '35': {'name': 'Bromine', 'atomicWeight': 79.904, 'symbol': 'Br'},
  '36': {'name': 'Krypton', 'atomicWeight': 83.798, 'symbol': 'Kr'},
  '37': {'name': 'Rubidium', 'atomicWeight': 85.468, 'symbol': 'Rb'},
  '38': {'name': 'Strontium', 'atomicWeight': 87.62, 'symbol': 'Sr'},
  '39': {'name': 'Yttrium', 'atomicWeight': 88.906, 'symbol': 'Y'},
  '40': {'name': 'Zirconium', 'atomicWeight': 91.224, 'symbol': 'Zr'},
  '41': {'name': 'Niobium', 'atomicWeight': 92.906, 'symbol': 'Nb'},
  '42': {'name': 'Molybdenur', 'atomicWeight': 95.95, 'symbol': 'Mo'},
  '43': {'name': 'Technetium', 'atomicWeight': 98, 'symbol': 'Tc'},
  '44': {'name': 'Ruthenium', 'atomicWeight': 101.07, 'symbol': 'Ru'},
  '45': {'name': 'Rhodium', 'atomicWeight': 102.91, 'symbol': 'Rh'},
  '46': {'name': 'Palladium', 'atomicWeight': 106.42, 'symbol': 'Pd'},
  '47': {'name': 'Silver', 'atomicWeight': 107.87, 'symbol': 'Ag'},
  '48': {'name': 'Cadmium', 'atomicWeight': 112.41, 'symbol': 'Cd'},
  '49': {'name': 'Indium', 'atomicWeight': 114.82, 'symbol': 'In'},
  '50': {'name': 'Tin', 'atomicWeight': 118.71, 'symbol': 'Sn'},
  '51': {'name': 'Antimony', 'atomicWeight': 121.76, 'symbol': 'Sb'},
  '52': {'name': 'Tellurium', 'atomicWeight': 127.60, 'symbol': 'Te'},
  '53': {'name': 'Iodine', 'atomicWeight': 126.90, 'symbol': 'I'},
  '54': {'name': 'Xenon', 'atomicWeight': 131.29, 'symbol': 'Xe'},
  '55': {'name': 'Caesium', 'atomicWeight': 132.91, 'symbol': 'Cs'},
  '56': {'name': 'Barium', 'atomicWeight': 137.3, 'symbol': 'Ba'},
  '57': {'name': 'Lanthanum', 'atomicWeight': 138.91, 'symbol': 'La'},
  '58': {'name': 'Cerium', 'atomicWeight': 140.12, 'symbol': 'Ce'},
  '59': {'name': 'Praseodynium', 'atomicWeight': 140.91, 'symbol': 'Pr'},
  '60': {'name': 'Neodynium', 'atomicWeight': 144.24, 'symbol': 'Nd'},
  '61': {'name': 'Promethium', 'atomicWeight': 145, 'symbol': 'Pm'},
  '62': {'name': 'Samarium', 'atomicWeight': 150.36, 'symbol': 'Sm'},
  '63': {'name': 'Europium', 'atomicWeight': 151.96, 'symbol': 'Eu'},
  '64': {'name': 'Gadolinium', 'atomicWeight': 157.25, 'symbol': 'Gd'},
  '65': {'name': 'Terbium', 'atomicWeight': 158.93, 'symbol': 'Tb'},
  '66': {'name': 'Dysprosium', 'atomicWeight': 162.5, 'symbol': 'Dy'},
  '67': {'name': 'Holmium', 'atomicWeight': 164.93, 'symbol': 'Ho'},
  '68': {'name': 'Erbium', 'atomicWeight': 167.26, 'symbol': 'Er'},
  '69': {'name': 'Thulium', 'atomicWeight': 168.93, 'symbol': 'Tm'},
  '70': {'name': 'Ytterbium', 'atomicWeight': 173.05, 'symbol': 'Yb'},
  '71': {'name': 'Lutetium', 'atomicWeight': 174.97, 'symbol': 'Lu'},
  '72': {'name': 'Hafnium', 'atomicWeight': 178.49, 'symbol': 'Hf'},
  '73': {'name': 'Tantalum', 'atomicWeight': 180.95, 'symbol': 'Ta'},
  '74': {'name': 'Tungsten', 'atomicWeight': 183.84, 'symbol': 'W'},
  '75': {'name': 'Rhenium', 'atomicWeight': 186.21, 'symbol': 'Re'},
  '76': {'name': 'Osmium', 'atomicWeight': 190.23, 'symbol': 'Os'},
  '77': {'name': 'Iridium', 'atomicWeight': 192.22, 'symbol': 'Ir'},
  '78': {'name': 'Platinum', 'atomicWeight': 195.08, 'symbol': 'Pt'},
  '79': {'name': 'Gold', 'atomicWeight': 196.97, 'symbol': 'Au'},
  '80': {'name': 'Mercury', 'atomicWeight': 200.59, 'symbol': 'Hg'},
  '81': {'name': 'Thallium', 'atomicWeight': 204.38, 'symbol': 'Tl'},
  '82': {'name': 'Lead', 'atomicWeight': 207.2, 'symbol': 'Pb'},
  '83': {'name': 'Bismuth', 'atomicWeight': 208.98, 'symbol': 'Bi'},
  '84': {'name': 'Polonium', 'atomicWeight': 209, 'symbol': 'Po'},
  '85': {'name': 'Astatine', 'atomicWeight': 210, 'symbol': 'At'},
  '86': {'name': 'Radon', 'atomicWeight': 222, 'symbol': 'Rn'},
  '87': {'name': 'Francium', 'atomicWeight': 223, 'symbol': 'Fr'},
  '88': {'name': 'Radium', 'atomicWeight': 226, 'symbol': 'Ra'},
  '89': {'name': 'Actinium', 'atomicWeight': 227, 'symbol': 'Ac'},
  '90': {'name': 'Thorium', 'atomicWeight': 232.04, 'symbol': 'Th'},
  '91': {'name': 'Protactinium', 'atomicWeight': 231.04, 'symbol': 'Pa'},
  '92': {'name': 'Uranium', 'atomicWeight': 238.03, 'symbol': 'U'},
  '93': {'name': 'Neptunium', 'atomicWeight': 237, 'symbol': 'Np'},
  '94': {'name': 'Plutonium', 'atomicWeight': 244, 'symbol': 'Pu'},
  '95': {'name': 'Americium', 'atomicWeight': 243, 'symbol': 'Am'},
  '96': {'name': 'Curium', 'atomicWeight': 247, 'symbol': 'Cm'},
  '97': {'name': 'Berkelium', 'atomicWeight': 247, 'symbol': 'Bk'},
  '98': {'name': 'Californium', 'atomicWeight': 251, 'symbol': 'Cf'},
  '99': {'name': 'Einsteinium', 'atomicWeight': 252, 'symbol': 'Es'},
  '100': {'name': 'Fermium', 'atomicWeight': 257, 'symbol': 'Fm'},
  '101': {'name': 'Mendelevium', 'atomicWeight': 258, 'symbol': 'Md'},
  '102': {'name': 'Nobelium', 'atomicWeight': 259, 'symbol': 'No'},
  '103': {'name': 'Lawrencium', 'atomicWeight': 266, 'symbol': 'Lr'},
  '104': {'name': 'Rutherfordium', 'atomicWeight': 267, 'symbol': 'Rf'},
  '105': {'name': 'Dubnium', 'atomicWeight': 268, 'symbol': 'Db'},
  '106': {'name': 'Seaborgium', 'atomicWeight': 269, 'symbol': 'Sg'},
  '107': {'name': 'Bohrium', 'atomicWeight': 270, 'symbol': 'Bh'},
  '108': {'name': 'Hassium', 'atomicWeight': 270, 'symbol': 'Hs'},
  '109': {'name': 'Meitnerium', 'atomicWeight': 278, 'symbol': 'Mt'},
  '110': {'name': 'Darmstadtium', 'atomicWeight': 281, 'symbol': 'Ds'},
  '111': {'name': 'Roentgenium', 'atomicWeight': 282, 'symbol': 'Rg'},
  '112': {'name': 'Copernicium', 'atomicWeight': 285, 'symbol': 'Cn'},
  '113': {'name': 'Nihonium', 'atomicWeight': 286, 'symbol': 'Nh'},
  '114': {'name': 'Flerovium', 'atomicWeight': 289, 'symbol': 'Fl'},
  '115': {'name': 'Moscovium', 'atomicWeight': 290, 'symbol': 'Mc'},
  '116': {'name': 'Livermorium', 'atomicWeight': 293, 'symbol': 'Lv'},
  '117': {'name': 'Tennessine', 'atomicWeight': 294, 'symbol': 'Ts'},
  '118': {'name': 'Oganesson', 'atomicWeight': 294, 'symbol': 'Og'},
};

Map countries = {
  'AFGHANISTAN': {'capital': 'KABUL'},
  'ALBANIA': {'capital': 'TIRANA'},
  'ALGERIA': {'capital': 'ALGIERS'},
  'ANDORRA': {'capital': 'ANDORRA LA VELLA'},
  'ANGOLA': {'capital': 'LUANDA'},
  'ANTIGUA & BARBUDA': {'capital': 'SAINT JOHN\'S'},
  'ARGENTINA': {'capital': 'BUENOS AIRES'},
  'ARMENIA': {'capital': 'YEREVAN'},
  'AUSTRALIA': {'capital': 'CANBERRA'},
  'AUSTRIA': {'capital': 'VIENNA'},
  'AZERBAIJAN': {'capital': 'BAKU'},
  'BAHAMAS, THE': {'capital': 'NASSAU'},
  'BAHRAIN': {'capital': 'MANAMA'},
  'BANGLADESH': {'capital': 'DHAKA'},
  'BARBADOS': {'capital': 'BRIDGETOWN'},
  'BELARUS': {'capital': 'MINSK'},
  'BELGIUM': {'capital': 'BRUSSELS'},
  'BELIZE': {'capital': 'BELMOPAN'},
  'BENIN': {'capital': 'PORTO-NOVO'},
  'BHUTAN': {'capital': 'THIMPHU'},
  'BOLIVIA': {'capital': 'SUCRE'},
  'BOSNIA & HERZEGOVINA': {'capital': 'SARAJEVO'},
  'BOTSWANA': {'capital': 'GABORONE'},
  'BRAZIL': {'capital': 'BRASILIA'},
  'BRUNEI': {'capital': 'BANDAR SERI BEGAWAN'},
  'BULGARIA': {'capital': 'SOFIA'},
  'BURKINA FASO': {'capital': 'OUAGADOUGOU'},
  'BURUNDI': {'capital': 'BUJUMBURA'},
  'CABO VERDE': {'capital': 'PRAIA'},
  'CAMBODIA': {'capital': 'PHNOM PENH'},
  'CAMEROON': {'capital': 'YAOUNDE'},
  'CANADA': {'capital': 'OTTAWA'},
  'CENTRAL AFRICAN REPUBLIC': {'capital': 'BANGUI'},
  'CHAD': {'capital': 'N\'DJAMENA'},
  'CHILE': {'capital': 'SANTIAGO'},
  'CHINA': {'capital': 'BEIJING'},
  'COLOMBIA': {'capital': 'BOGOTÁ'},
  'COMOROS': {'capital': 'MORONI'},
  'CONGO, DEMOCRATIC REPUBLIC OF THE': {'capital': 'KINSHASA'},
  'COSTA RICA': {'capital': 'SAN JOSE'},
  'CÔTE D\'IVOIRE': {'capital': 'YAMOUSSOUKRO'},
  'CROATIA': {'capital': 'ZAGREB'},
  'CUBA': {'capital': 'HAVANA'},
  'CYPRUS': {'capital': 'NICOSIA'},
  'CZECH REPUBLIC': {'capital': 'PRAGUE'},
  'DENMARK': {'capital': 'COPENHAGEN'},
  'DJIBOUTI': {'capital': 'DJIBOUTI (CITY)'},
  'DOMINICA': {'capital': 'ROSEAU'},
  'DOMINICAN REPUBLIC': {'capital': 'SANTO DOMINGO'},
  'ECUADOR': {'capital': 'QUITO'},
  'EGYPT': {'capital': 'CAIRO'},
  'EL SALVADOR': {'capital': 'SAN SALVADOR'},
  'EQUATORIAL GUINEA': {'capital': 'MALABO'},
  'ERITREA': {'capital': 'ASMARA'},
  'ESTONIA': {'capital': 'TALLINN'},
  'ESWATINI': {'capital': 'MBABANE'},
  'ETHIOPIA': {'capital': 'ADDIS ABABA'},
  'FEDERATED STATES OF MICRONESIA': {'capital': 'PALIKIR'},
  'FIJI': {'capital': 'SUVA'},
  'FINLAND': {'capital': 'HELSINKI'},
  'FRANCE': {'capital': 'PARIS'},
  'GABON': {'capital': 'LIBREVILLE'},
  'GAMBIA, THE': {'capital': 'BANJUL'},
  'GEORGIA': {'capital': 'TBILISI'},
  'GERMANY': {'capital': 'BERLIN'},
  'GHANA': {'capital': 'ACCRA'},
  'GREECE': {'capital': 'ATHENS'},
  'GRENADA': {'capital': 'SAINT GEORGE\'S'},
  'GUATEMALA': {'capital': 'GUATEMALA CITY'},
  'GUINEA': {'capital': 'CONAKRY'},
  'GUINEA-BISSAU': {'capital': 'BISSAU'},
  'GUYANA': {'capital': 'GEORGETOWN'},
  'HAITI': {'capital': 'PORT-AU-PRINCE'},
  'HONDURAS': {'capital': 'TEGUCIGALPA'},
  'HUNGARY': {'capital': 'BUDAPEST'},
  'ICELAND': {'capital': 'REYKJAVIK'},
  'INDIA': {'capital': 'NEW DELHI'},
  'INDONESIA': {'capital': 'JAKARTA'},
  'IRAN': {'capital': 'TEHRAN'},
  'IRAQ': {'capital': 'BAGHDAD'},
  'IRELAND': {'capital': 'DUBLIN'},
  'ISRAEL': {'capital': 'JERUSALEM'},
  'ITALY': {'capital': 'ROME'},
  'JAMAICA': {'capital': 'KINGSTON'},
  'JAPAN': {'capital': 'TOKYO'},
  'JORDAN': {'capital': 'AMMAN'},
  'KAZAKHSTAN': {'capital': 'NUR-SULTAN'},
  'KENYA': {'capital': 'NAIROBI'},
  'KIRIBATI': {'capital': 'SOUTH TARAWA'},
  'KOSOVO': {'capital': 'PRISTINA'},
  'KUWAIT': {'capital': 'KUWAIT CITY'},
  'KYRGYZSTAN': {'capital': 'BISHKEK'},
  'LAOS': {'capital': 'VIENTIANE'},
  'LATVIA': {'capital': 'RIGA'},
  'LEBANON': {'capital': 'BEIRUT'},
  'LESOTHO': {'capital': 'MASERU'},
  'LIBERIA': {'capital': 'MONROVIA'},
  'LIBYA': {'capital': 'TRIPOLI'},
  'LIECHTENSTEIN': {'capital': 'VADUZ'},
  'LITHUANIA': {'capital': 'VILNIUS'},
  'LUXEMBOURG': {'capital': 'LUXEMBOURG'},
  'MADAGASCAR': {'capital': 'ANTANANARIVO'},
  'MALAWI': {'capital': 'LILONGWE'},
  'MALAYSIA': {'capital': 'KUALA LUMPUR'},
  'MALDIVES': {'capital': 'MALE'},
  'MALI': {'capital': 'BAMAKO'},
  'MALTA': {'capital': 'VALLETTA'},
  'MARSHALL ISLANDS': {'capital': 'MAJURO'},
  'MAURITANIA': {'capital': 'NOUAKCHOTT'},
  'MAURITIUS': {'capital': 'PORT LOUIS'},
  'MEXICO': {'capital': 'MEXICO CITY'},
  'MOLDOVA': {'capital': 'CHISINAU'},
  'MONACO': {'capital': 'MONACO'},
  'MONGOLIA': {'capital': 'ULAANBAATAR'},
  'MONTENEGRO': {'capital': 'PODGORICA'},
  'MOROCCO': {'capital': 'RABAT'},
  'MOZAMBIQUE': {'capital': 'MAPUTO'},
  'MYANMAR': {'capital': 'NAY PYI TAW'},
  'NAMIBIA': {'capital': 'WINDHOEK'},
  'NAURU': {'capital': 'YAREN DISTRICT'},
  'NEPAL': {'capital': 'KATHMANDU'},
  'NETHERLANDS': {'capital': 'AMSTERDAM'},
  'NEW ZEALAND': {'capital': 'WELLINGTON'},
  'NICARAGUA': {'capital': 'MANAGUA'},
  'NIGER': {'capital': 'NIAMEY'},
  'NIGERIA': {'capital': 'ABUJA'},
  'NORTH KOREA': {'capital': 'PYONGYANG'},
  'NORTH MACEDONIA': {'capital': 'SKOPJE'},
  'NORWAY': {'capital': 'OSLO'},
  'OMAN': {'capital': 'MUSCAT'},
  'PAKISTAN': {'capital': 'ISLAMABAD'},
  'PALAU': {'capital': 'NGERULMUD'},
  'PALESTINE': {'capital': 'EAST JERUSALEM'},
  'PANAMA': {'capital': 'PANAMA CITY'},
  'PAPUA NEW GUINEA': {'capital': 'PORT MORESBY'},
  'PARAGUAY': {'capital': 'ASUNCIÓN'},
  'PERU': {'capital': 'LIMA'},
  'PHILIPPINES': {'capital': 'MANILA'},
  'POLAND': {'capital': 'WARSAW'},
  'PORTUGAL': {'capital': 'LISBON'},
  'QATAR': {'capital': 'DOHA'},
  'REPUBLIC OF THE CONGO': {'capital': 'BRAZZAVILLE'},
  'ROMANIA': {'capital': 'BUCHAREST'},
  'RUSSIA': {'capital': 'MOSCOW'},
  'RWANDA': {'capital': 'KIGALI'},
  'SAINT KITTS & NEVIS': {'capital': 'BASSETERRE'},
  'SAINT LUCIA': {'capital': 'CASTRIES'},
  'SAINT VINCENT & THE GRENADINES': {'capital': 'KINGSTOWN'},
  'SAMOA': {'capital': 'APIA'},
  'SAN MARINO': {'capital': 'SAN MARINO'},
  'SÃO TOMÉ & PRÍNCIPE': {'capital': 'SÃO TOMÉ'},
  'SAUDI ARABIA': {'capital': 'RIYADH'},
  'SENEGAL': {'capital': 'DAKAR'},
  'SERBIA': {'capital': 'BELGRADE'},
  'SEYCHELLES': {'capital': 'VICTORIA'},
  'SIERRA LEONE': {'capital': 'FREETOWN'},
  'SINGAPORE': {'capital': 'SINGAPORE'},
  'SLOVAKIA': {'capital': 'BRATISLAVA'},
  'SLOVENIA': {'capital': 'LJUBLJANA'},
  'SOLOMON ISLANDS': {'capital': 'HONIARA'},
  'SOMALIA': {'capital': 'MOGADISHU'},
  'SOUTH AFRICA': {'capital': 'BLOEMFONTEIN, CAPE TOWN, PRETORIA'},
  'SOUTH KOREA': {'capital': 'SEOUL'},
  'SOUTH SUDAN': {'capital': 'JUBA'},
  'SPAIN': {'capital': 'MADRID'},
  'SRI LANKA': {'capital': 'COLOMBO, SRI JAYAWARDENEPURA KOTTE'},
  'SUDAN': {'capital': 'KHARTOUM'},
  'SURINAME': {'capital': 'PARAMARIBO'},
  'SWEDEN': {'capital': 'STOCKHOLM'},
  'SWITZERLAND': {'capital': 'BERN'},
  'SYRIA': {'capital': 'DAMASCUS'},
  'TAJIKISTAN': {'capital': 'DUSHANBE'},
  'TANZANIA': {'capital': 'DODOMA'},
  'THAILAND': {'capital': 'BANGKOK'},
  'TIMOR-LESTE': {'capital': 'DILI'},
  'TOGO': {'capital': 'LOMÉ'},
  'TONGA': {'capital': 'NUKUʻALOFA'},
  'TRINIDAD & TOBAGO': {'capital': 'PORT OF SPAIN'},
  'TUNISIA': {'capital': 'TUNIS'},
  'TURKEY': {'capital': 'ANKARA'},
  'TURKMENISTAN': {'capital': 'ASHGABAT'},
  'TUVALU': {'capital': 'FUNAFUTI'},
  'UGANDA': {'capital': 'KAMPALA'},
  'UKRAINE': {'capital': 'KIEV'},
  'UNITED ARAB EMIRATES': {'capital': 'ABU DHABI'},
  'UNITED KINGDOM*': {'capital': 'LONDON'},
  'UNITED STATES': {'capital': 'WASHINGTON, D.C.'},
  'URUGUAY': {'capital': 'MONTEVIDEO'},
  'UZBEKISTAN': {'capital': 'TASHKENT'},
  'VANUATU': {'capital': 'PORT VILA'},
  'VATICAN CITY': {'capital': 'VATICAN CITY'},
  'VENEZUELA': {'capital': 'CARACAS'},
  'VIETNAM': {'capital': 'HANOI'},
  'YEMEN': {'capital': 'SANA\'A'},
  'ZAMBIA': {'capital': 'LUSAKA'},
  'ZIMBABWE': {'capital': 'HARARE'},
};

List<String> menNames = [
  'Liam',
  'Noah',
  'William',
  'James',
  'Oliver',
  'Benjamin',
  'Elijah',
  'Lucas',
  'Mason',
  'Logan',
  'Alexander',
  'Ethan',
  'Jacob',
  'Michael',
  'Daniel',
  'Henry',
  'Jackson',
  'Sebastian',
  'Aiden',
  'Matthew',
  'Samuel',
  'David',
  'Joseph',
  'Carter',
  'Owen',
  'Wyatt',
  'John',
  'Jack',
  'Luke',
  'Jayden',
  'Dylan',
  'Grayson',
  'Levi',
  'Isaac',
  'Gabriel',
  'Julian',
  'Mateo',
  'Anthony',
  'Jaxon',
  'Lincoln',
  'Joshua',
  'Christopher',
  'Andrew',
  'Theodore',
  'Caleb',
  'Ryan',
  'Asher',
  'Nathan',
  'Thomas',
  'Leo',
  'Isaiah',
  'Charles',
  'Josiah',
  'Hudson',
  'Christian',
  'Hunter',
  'Connor',
  'Eli',
  'Ezra',
  'Aaron',
  'Landon',
  'Adrian',
  'Jonathan',
  'Nolan',
  'Jeremiah',
  'Easton',
  'Elias',
  'Colton',
  'Cameron',
  'Carson',
  'Robert',
  'Angel',
  'Maverick',
  'Nicholas',
  'Dominic',
  'Jaxson',
  'Greyson',
  'Adam',
  'Ian',
  'Austin',
  'Santiago',
  'Jordan',
  'Cooper',
  'Brayden',
  'Roman',
  'Evan',
  'Ezekiel',
  'Xavier',
  'Jose',
  'Jace',
  'Jameson',
  'Leonardo',
  'Bryson',
  'Axel',
  'Everett',
  'Parker',
  'Kayden',
  'Miles',
  'Sawyer',
  'Jason',
  'Declan',
  'Weston',
  'Micah',
  'Ayden',
  'Wesley',
  'Luca',
  'Vincent',
  'Damian',
  'Zachary',
  'Silas',
  'Gavin',
  'Chase',
  'Kai',
  'Emmett',
  'Harrison',
  'Nathaniel',
  'Kingston',
  'Cole',
  'Tyler',
  'Bennett',
  'Bentley',
  'Ryker',
  'Tristan',
  'Brandon',
  'Kevin',
  'Luis',
  'George',
  'Ashton',
  'Rowan',
  'Braxton',
  'Ryder',
  'Gael',
  'Ivan',
  'Diego',
  'Maxwell',
  'Max',
  'Carlos',
  'Kaiden',
  'Juan',
  'Maddox',
  'Justin',
  'Waylon',
  'Calvin',
  'Giovanni',
  'Jonah',
  'Abel',
  'Jayce',
  'Jesus',
  'Amir',
  'King',
  'Beau',
  'Camden',
  'Alex',
  'Jasper',
  'Malachi',
  'Brody',
  'Jude',
  'Blake',
  'Emmanuel',
  'Eric',
  'Brooks',
  'Elliot',
  'Antonio',
  'Abraham',
  'Timothy',
  'Finn',
  'Rhett',
  'Elliott',
  'Edward',
  'August',
  'Xander',
  'Alan',
  'Dean',
  'Lorenzo',
  'Bryce',
  'Karter',
  'Victor',
  'Milo',
  'Miguel',
  'Hayden',
  'Graham',
  'Grant',
  'Zion',
  'Tucker',
  'Jesse',
  'Zayden',
  'Joel',
  'Richard',
  'Patrick',
  'Emiliano',
  'Avery',
  'Nicolas',
  'Brantley',
  'Dawson',
  'Myles',
  'Matteo',
  'River',
  'Steven',
  'Thiago',
  'Zane',
  'Matias',
  'Judah',
  'Messiah',
  'Jeremy',
  'Preston',
  'Oscar',
  'Kaleb',
  'Alejandro',
  'Marcus',
  'Mark',
  'Peter',
  'Maximus',
  'Barrett',
  'Jax',
  'Andres',
  'Holden',
  'Legend',
  'Charlie',
  'Knox',
  'Kaden',
  'Paxton',
  'Kyrie',
  'Kyle',
  'Griffin',
  'Josue',
  'Kenneth',
  'Beckett',
  'Enzo',
  'Adriel',
  'Arthur',
  'Felix',
  'Bryan',
  'Lukas',
  'Paul',
  'Brian',
  'Colt',
  'Caden',
  'Leon',
  'Archer',
  'Omar',
  'Israel',
  'Aidan',
  'Theo',
  'Javier',
  'Remington',
  'Jaden',
  'Bradley',
  'Emilio',
  'Colin',
  'Riley',
  'Cayden',
  'Phoenix',
  'Clayton',
  'Simon',
  'Ace',
  'Nash',
  'Derek',
  'Rafael',
  'Zander',
  'Brady',
  'Jorge',
  'Jake',
  'Louis',
  'Damien',
  'Karson',
  'Walker',
  'Maximiliano',
  'Amari',
  'Sean',
  'Chance',
  'Walter',
  'Martin',
  'Finley',
  'Andre',
  'Tobias',
  'Cash',
  'Corbin',
  'Arlo',
  'Iker',
  'Erick',
  'Emerson',
  'Gunner',
  'Cody',
  'Stephen',
  'Francisco',
  'Killian',
  'Dallas',
  'Reid',
  'Manuel',
  'Lane',
  'Atlas',
  'Rylan',
  'Jensen',
  'Ronan',
  'Beckham',
  'Daxton',
  'Anderson',
  'Kameron',
  'Raymond',
  'Orion',
  'Cristian',
  'Tanner',
  'Kyler',
  'Jett',
  'Cohen',
  'Ricardo',
  'Spencer',
  'Gideon',
  'Ali',
  'Fernando',
  'Jaiden',
  'Titus',
  'Travis',
  'Bodhi',
  'Eduardo',
  'Dante',
  'Ellis',
  'Prince',
  'Kane',
  'Luka',
  'Kash',
  'Hendrix',
  'Desmond',
  'Donovan',
  'Mario',
  'Atticus',
  'Cruz',
  'Garrett',
  'Hector',
  'Angelo',
  'Jeffrey',
  'Edwin',
  'Cesar',
  'Zayn',
  'Devin',
  'Conor',
  'Warren',
  'Odin',
  'Jayceon',
  'Romeo',
  'Julius',
  'Jaylen',
  'Hayes',
  'Kayson',
  'Muhammad',
  'Jaxton',
  'Joaquin',
  'Caiden',
  'Dakota',
  'Major',
  'Keegan',
  'Sergio',
  'Marshall',
  'Johnny',
  'Kade',
  'Edgar',
  'Leonel',
  'Ismael',
  'Marco',
  'Tyson',
  'Wade',
  'Collin',
  'Troy',
  'Nasir',
  'Conner',
  'Adonis',
  'Jared',
  'Rory',
  'Andy',
  'Jase',
  'Lennox',
  'Shane',
  'Malik',
  'Ari',
  'Reed',
  'Seth',
  'Clark',
  'Erik',
  'Lawson',
  'Trevor',
  'Gage',
  'Nico',
  'Malakai',
  'Quinn',
  'Cade',
  'Johnathan',
  'Sullivan',
  'Solomon',
  'Cyrus',
  'Fabian',
  'Pedro',
  'Frank',
  'Shawn',
  'Malcolm',
  'Khalil',
  'Nehemiah',
  'Dalton',
  'Mathias',
  'Jay',
  'Ibrahim',
  'Peyton',
  'Winston',
  'Kason',
  'Zayne',
  'Noel',
  'Princeton',
  'Matthias',
  'Gregory',
  'Sterling',
  'Dominick',
  'Elian',
  'Grady',
  'Russell',
  'Finnegan',
  'Ruben',
  'Gianni',
  'Porter',
  'Kendrick',
  'Leland',
  'Pablo',
  'Allen',
  'Hugo',
  'Raiden',
  'Kolton',
  'Remy',
  'Ezequiel',
  'Damon',
  'Emanuel',
  'Zaiden',
  'Otto',
  'Bowen',
  'Marcos',
  'Abram',
  'Kasen',
  'Franklin',
  'Royce',
  'Jonas',
  'Sage',
  'Philip',
  'Esteban',
  'Drake',
  'Kashton',
  'Roberto',
  'Harvey',
  'Alexis',
  'Kian',
  'Jamison',
  'Maximilian',
  'Adan',
  'Milan',
  'Phillip',
  'Albert',
  'Dax',
  'Mohamed',
  'Ronin',
  'Kamden',
  'Hank',
  'Memphis',
  'Oakley',
  'Augustus',
  'Drew',
  'Moises',
  'Armani',
  'Rhys',
  'Benson',
  'Jayson',
  'Kyson',
  'Braylen',
  'Corey',
  'Gunnar',
  'Omari',
  'Alonzo',
  'Landen',
  'Armando',
  'Derrick',
  'Dexter',
  'Enrique',
  'Bruce',
  'Nikolai',
  'Francis',
  'Rocco',
  'Kairo',
  'Royal',
  'Zachariah',
  'Arjun',
  'Deacon',
  'Skyler',
  'Eden',
  'Alijah',
  'Rowen',
  'Pierce',
  'Uriel',
  'Ronald',
  'Luciano',
  'Tate',
  'Frederick',
  'Kieran',
  'Lawrence',
  'Moses',
  'Rodrigo'
];
List<String> womenNames = [
  'Emma',
  'Olivia',
  'Ava',
  'Isabella',
  'Sophia',
  'Charlotte',
  'Mia',
  'Amelia',
  'Harper',
  'Evelyn',
  'Abigail',
  'Emily',
  'Elizabeth',
  'Mila',
  'Ella',
  'Avery',
  'Sofia',
  'Camila',
  'Aria',
  'Scarlett',
  'Victoria',
  'Madison',
  'Luna',
  'Grace',
  'Chloe',
  'Penelope',
  'Layla',
  'Riley',
  'Zoey',
  'Nora',
  'Lily',
  'Eleanor',
  'Hannah',
  'Lillian',
  'Addison',
  'Aubrey',
  'Ellie',
  'Stella',
  'Natalie',
  'Zoe',
  'Leah',
  'Hazel',
  'Violet',
  'Aurora',
  'Savannah',
  'Audrey',
  'Brooklyn',
  'Bella',
  'Claire',
  'Skylar',
  'Lucy',
  'Paisley',
  'Everly',
  'Anna',
  'Caroline',
  'Nova',
  'Genesis',
  'Emilia',
  'Kennedy',
  'Samantha',
  'Maya',
  'Willow',
  'Kinsley',
  'Naomi',
  'Aaliyah',
  'Elena',
  'Sarah',
  'Ariana',
  'Allison',
  'Gabriella',
  'Alice',
  'Madelyn',
  'Cora',
  'Ruby',
  'Eva',
  'Serenity',
  'Autumn',
  'Adeline',
  'Hailey',
  'Gianna',
  'Valentina',
  'Isla',
  'Eliana',
  'Quinn',
  'Nevaeh',
  'Ivy',
  'Sadie',
  'Piper',
  'Lydia',
  'Alexa',
  'Josephine',
  'Emery',
  'Julia',
  'Delilah',
  'Arianna',
  'Vivian',
  'Kaylee',
  'Sophie',
  'Brielle',
  'Madeline',
  'Peyton',
  'Rylee',
  'Clara',
  'Hadley',
  'Melanie',
  'Mackenzie',
  'Reagan',
  'Adalynn',
  'Liliana',
  'Aubree',
  'Jade',
  'Katherine',
  'Isabelle',
  'Natalia',
  'Raelynn',
  'Maria',
  'Athena',
  'Ximena',
  'Arya',
  'Leilani',
  'Taylor',
  'Faith',
  'Rose',
  'Kylie',
  'Alexandra',
  'Mary',
  'Margaret',
  'Lyla',
  'Ashley',
  'Amaya',
  'Eliza',
  'Brianna',
  'Bailey',
  'Andrea',
  'Khloe',
  'Jasmine',
  'Melody',
  'Iris',
  'Isabel',
  'Norah',
  'Annabelle',
  'Valeria',
  'Emerson',
  'Adalyn',
  'Ryleigh',
  'Eden',
  'Emersyn',
  'Anastasia',
  'Kayla',
  'Alyssa',
  'Juliana',
  'Charlie',
  'Esther',
  'Ariel',
  'Cecilia',
  'Valerie',
  'Alina',
  'Molly',
  'Reese',
  'Aliyah',
  'Lilly',
  'Parker',
  'Finley',
  'Morgan',
  'Sydney',
  'Jordyn',
  'Eloise',
  'Trinity',
  'Daisy',
  'Kimberly',
  'Lauren',
  'Genevieve',
  'Sara',
  'Arabella',
  'Harmony',
  'Elise',
  'Remi',
  'Teagan',
  'Alexis',
  'London',
  'Sloane',
  'Laila',
  'Lucia',
  'Diana',
  'Juliette',
  'Sienna',
  'Elliana',
  'Londyn',
  'Ayla',
  'Callie',
  'Gracie',
  'Josie',
  'Amara',
  'Jocelyn',
  'Daniela',
  'Everleigh',
  'Mya',
  'Rachel',
  'Summer',
  'Alana',
  'Brooke',
  'Alaina',
  'Mckenzie',
  'Catherine',
  'Amy',
  'Presley',
  'Journee',
  'Rosalie',
  'Ember',
  'Brynlee',
  'Rowan',
  'Joanna',
  'Paige',
  'Rebecca',
  'Ana',
  'Sawyer',
  'Mariah',
  'Nicole',
  'Brooklynn',
  'Payton',
  'Marley',
  'Fiona',
  'Georgia',
  'Lila',
  'Harley',
  'Adelyn',
  'Alivia',
  'Noelle',
  'Gemma',
  'Vanessa',
  'Journey',
  'Makayla',
  'Angelina',
  'Adaline',
  'Catalina',
  'Alayna',
  'Julianna',
  'Leila',
  'Lola',
  'Adriana',
  'June',
  'Juliet',
  'Jayla',
  'River',
  'Tessa',
  'Lia',
  'Dakota',
  'Delaney',
  'Selena',
  'Blakely',
  'Ada',
  'Camille',
  'Zara',
  'Malia',
  'Hope',
  'Samara',
  'Vera',
  'Mckenna',
  'Briella',
  'Izabella',
  'Hayden',
  'Raegan',
  'Michelle',
  'Angela',
  'Ruth',
  'Freya',
  'Kamila',
  'Vivienne',
  'Aspen',
  'Olive',
  'Kendall',
  'Elaina',
  'Thea',
  'Kali',
  'Destiny',
  'Amiyah',
  'Evangeline',
  'Cali',
  'Blake',
  'Elsie',
  'Juniper',
  'Alexandria',
  'Myla',
  'Ariella',
  'Kate',
  'Mariana',
  'Lilah',
  'Charlee',
  'Daleyza',
  'Nyla',
  'Jane',
  'Maggie',
  'Zuri',
  'Aniyah',
  'Lucille',
  'Leia',
  'Melissa',
  'Adelaide',
  'Amina',
  'Giselle',
  'Lena',
  'Camilla',
  'Miriam',
  'Millie',
  'Brynn',
  'Gabrielle',
  'Sage',
  'Annie',
  'Logan',
  'Lilliana',
  'Haven',
  'Jessica',
  'Kaia',
  'Magnolia',
  'Amira',
  'Adelynn',
  'Makenzie',
  'Stephanie',
  'Nina',
  'Phoebe',
  'Arielle',
  'Evie',
  'Lyric',
  'Alessandra',
  'Gabriela',
  'Paislee',
  'Raelyn',
  'Madilyn',
  'Paris',
  'Makenna',
  'Kinley',
  'Gracelyn',
  'Talia',
  'Maeve',
  'Rylie',
  'Kiara',
  'Evelynn',
  'Brinley',
  'Jacqueline',
  'Laura',
  'Gracelynn',
  'Lexi',
  'Ariah',
  'Fatima',
  'Jennifer',
  'Kehlani',
  'Alani',
  'Ariyah',
  'Luciana',
  'Allie',
  'Heidi',
  'Maci',
  'Phoenix',
  'Felicity',
  'Joy',
  'Kenzie',
  'Veronica',
  'Margot',
  'Addilyn',
  'Lana',
  'Cassidy',
  'Remington',
  'Saylor',
  'Ryan',
  'Keira',
  'Harlow',
  'Miranda',
  'Angel',
  'Amanda',
  'Daniella',
  'Royalty',
  'Gwendolyn',
  'Ophelia',
  'Heaven',
  'Jordan',
  'Madeleine',
  'Esmeralda',
  'Kira',
  'Miracle',
  'Elle',
  'Amari',
  'Danielle',
  'Daphne',
  'Willa',
  'Haley',
  'Gia',
  'Kaitlyn',
  'Oakley',
  'Kailani',
  'Winter',
  'Alicia',
  'Serena',
  'Nadia',
  'Aviana',
  'Demi',
  'Jada',
  'Braelynn',
  'Dylan',
  'Ainsley',
  'Alison',
  'Camryn',
  'Avianna',
  'Bianca',
  'Skyler',
  'Scarlet',
  'Maddison',
  'Nylah',
  'Sarai',
  'Regina',
  'Dahlia',
  'Nayeli',
  'Raven',
  'Helen',
  'Adrianna',
  'Averie',
  'Skye',
  'Kelsey',
  'Tatum',
  'Kensley',
  'Maliyah',
  'Erin',
  'Viviana',
  'Jenna',
  'Anaya',
  'Carolina',
  'Shelby',
  'Sabrina',
  'Mikayla',
  'Annalise',
  'Octavia',
  'Lennon',
  'Blair',
  'Carmen',
  'Yaretzi',
  'Kennedi',
  'Mabel',
  'Zariah',
  'Kyla',
  'Christina',
  'Selah',
  'Celeste',
  'Eve',
  'Mckinley',
  'Milani',
  'Frances',
  'Jimena',
  'Kylee',
  'Leighton',
  'Katie',
  'Aitana',
  'Kayleigh',
  'Sierra',
  'Kathryn',
  'Rosemary',
  'Jolene',
  'Alondra',
  'Elisa',
  'Helena',
  'Charleigh',
  'Hallie',
  'Lainey',
  'Avah',
  'Jazlyn',
  'Kamryn',
  'Mira',
  'Cheyenne',
  'Francesca',
  'Antonella',
  'Wren',
  'Chelsea',
  'Amber',
  'Emory',
  'Lorelei',
  'Nia',
  'Abby',
  'April',
  'Emelia',
  'Carter',
  'Aylin',
  'Cataleya',
  'Bethany',
  'Marlee',
  'Carly',
  'Kaylani',
  'Emely',
  'Liana',
  'Madelynn',
  'Cadence',
  'Matilda',
  'Sylvia',
  'Myra',
  'Fernanda',
  'Oaklyn',
  'Elianna',
  'Hattie',
  'Dayana',
  'Kendra',
  'Maisie',
  'Malaysia',
  'Kara'
];

List<String> lastNames = [
  'SMITH',
  'JOHNSON',
  'WILLIAMS',
  'JONES',
  'BROWN',
  'DAVIS',
  'MILLER',
  'WILSON',
  'MOORE',
  'TAYLOR',
  'ANDERSON',
  'THOMAS',
  'JACKSON',
  'WHITE',
  'HARRIS',
  'MARTIN',
  'THOMPSON',
  'GARCIA',
  'MARTINEZ',
  'ROBINSON',
  'CLARK',
  'RODRIGUEZ',
  'LEWIS',
  'LEE',
  'WALKER',
  'HALL',
  'ALLEN',
  'YOUNG',
  'HERNANDEZ',
  'KING',
  'WRIGHT',
  'LOPEZ',
  'HILL',
  'SCOTT',
  'GREEN',
  'ADAMS',
  'BAKER',
  'GONZALEZ',
  'NELSON',
  'CARTER',
  'MITCHELL',
  'PEREZ',
  'ROBERTS',
  'TURNER',
  'PHILLIPS',
  'CAMPBELL',
  'PARKER',
  'EVANS',
  'EDWARDS',
  'COLLINS',
  'STEWART',
  'SANCHEZ',
  'MORRIS',
  'ROGERS',
  'REED',
  'COOK',
  'MORGAN',
  'BELL',
  'MURPHY',
  'BAILEY',
  'RIVERA',
  'COOPER',
  'RICHARDSON',
  'COX',
  'HOWARD',
  'WARD',
  'TORRES',
  'PETERSON',
  'GRAY',
  'RAMIREZ',
  'JAMES',
  'WATSON',
  'BROOKS',
  'KELLY',
  'SANDERS',
  'PRICE',
  'BENNETT',
  'WOOD',
  'BARNES',
  'ROSS',
  'HENDERSON',
  'COLEMAN',
  'JENKINS',
  'PERRY',
  'POWELL',
  'LONG',
  'PATTERSON',
  'HUGHES',
  'FLORES',
  'WASHINGTON',
  'BUTLER',
  'SIMMONS',
  'FOSTER',
  'GONZALES',
  'BRYANT',
  'ALEXANDER',
  'RUSSELL',
  'GRIFFIN',
  'DIAZ',
  'HAYES',
  'MYERS',
  'FORD',
  'HAMILTON',
  'GRAHAM',
  'SULLIVAN',
  'WALLACE',
  'WOODS',
  'COLE',
  'WEST',
  'JORDAN',
  'OWENS',
  'REYNOLDS',
  'FISHER',
  'ELLIS',
  'HARRISON',
  'GIBSON',
  'MCDONALD',
  'CRUZ',
  'MARSHALL',
  'ORTIZ',
  'GOMEZ',
  'MURRAY',
  'FREEMAN',
  'WELLS',
  'WEBB',
  'SIMPSON',
  'STEVENS',
  'TUCKER',
  'PORTER',
  'HUNTER',
  'HICKS',
  'CRAWFORD',
  'HENRY',
  'BOYD',
  'MASON',
  'MORALES',
  'KENNEDY',
  'WARREN',
  'DIXON',
  'RAMOS',
  'REYES',
  'BURNS',
  'GORDON',
  'SHAW',
  'HOLMES',
  'RICE',
  'ROBERTSON',
  'HUNT',
  'BLACK',
  'DANIELS',
  'PALMER',
  'MILLS',
  'NICHOLS',
  'GRANT',
  'KNIGHT',
  'FERGUSON',
  'ROSE',
  'STONE',
  'HAWKINS',
  'DUNN',
  'PERKINS',
  'HUDSON',
  'SPENCER',
  'GARDNER',
  'STEPHENS',
  'PAYNE',
  'PIERCE',
  'BERRY',
  'MATTHEWS',
  'ARNOLD',
  'WAGNER',
  'WILLIS',
  'RAY',
  'WATKINS',
  'OLSON',
  'CARROLL',
  'DUNCAN',
  'SNYDER',
  'HART',
  'CUNNINGHAM',
  'BRADLEY',
  'LANE',
  'ANDREWS',
  'RUIZ',
  'HARPER',
  'FOX',
  'RILEY',
  'ARMSTRONG',
  'CARPENTER',
  'WEAVER',
  'GREENE',
  'LAWRENCE',
  'ELLIOTT',
  'CHAVEZ',
  'SIMS',
  'AUSTIN',
  'PETERS',
  'KELLEY',
  'FRANKLIN',
  'LAWSON',
  'FIELDS',
  'GUTIERREZ',
  'RYAN',
  'SCHMIDT',
  'CARR',
  'VASQUEZ',
  'CASTILLO',
  'WHEELER',
  'CHAPMAN',
  'OLIVER',
  'MONTGOMERY',
  'RICHARDS',
  'WILLIAMSON',
  'JOHNSTON',
  'BANKS',
  'MEYER',
  'BISHOP',
  'MCCOY',
  'HOWELL',
  'ALVAREZ',
  'MORRISON',
  'HANSEN',
  'FERNANDEZ',
  'GARZA',
  'HARVEY',
  'LITTLE',
  'BURTON',
  'STANLEY',
  'NGUYEN',
  'GEORGE',
  'JACOBS',
  'REID',
  'KIM',
  'FULLER',
  'LYNCH',
  'DEAN',
  'GILBERT',
  'GARRETT',
  'ROMERO',
  'WELCH',
  'LARSON',
  'FRAZIER',
  'BURKE',
  'HANSON',
  'DAY',
  'MENDOZA',
  'MORENO',
  'BOWMAN',
  'MEDINA',
  'FOWLER',
  'BREWER',
  'HOFFMAN',
  'CARLSON',
  'SILVA',
  'PEARSON',
  'HOLLAND',
  'DOUGLAS',
  'FLEMING',
  'JENSEN',
  'VARGAS',
  'BYRD',
  'DAVIDSON',
  'HOPKINS',
  'MAY',
  'TERRY',
  'HERRERA',
  'WADE',
  'SOTO',
  'WALTERS',
  'CURTIS',
  'NEAL',
  'CALDWELL',
  'LOWE',
  'JENNINGS',
  'BARNETT',
  'GRAVES',
  'JIMENEZ',
  'HORTON',
  'SHELTON',
  'BARRETT',
  'OBRIEN',
  'CASTRO',
  'SUTTON',
  'GREGORY',
  'MCKINNEY',
  'LUCAS',
  'MILES',
  'CRAIG',
  'RODRIQUEZ',
  'CHAMBERS',
  'HOLT',
  'LAMBERT',
  'FLETCHER',
  'WATTS',
  'BATES',
  'HALE',
  'RHODES',
  'PENA',
  'BECK',
  'NEWMAN',
  'HAYNES',
  'MCDANIEL',
  'MENDEZ',
  'BUSH',
  'VAUGHN',
  'PARKS',
  'DAWSON',
  'SANTIAGO',
  'NORRIS',
  'HARDY',
  'LOVE',
  'STEELE',
  'CURRY',
  'POWERS',
  'SCHULTZ',
  'BARKER',
  'GUZMAN',
  'PAGE',
  'MUNOZ',
  'BALL',
  'KELLER',
  'CHANDLER',
  'WEBER',
  'LEONARD',
  'WALSH',
  'LYONS',
  'RAMSEY',
  'WOLFE',
  'SCHNEIDER',
  'MULLINS',
  'BENSON',
  'SHARP',
  'BOWEN',
  'DANIEL',
  'BARBER',
  'CUMMINGS',
  'HINES',
  'BALDWIN',
  'GRIFFITH',
  'VALDEZ',
  'HUBBARD',
  'SALAZAR',
  'REEVES',
  'WARNER',
  'STEVENSON',
  'BURGESS',
  'SANTOS',
  'TATE',
  'CROSS',
  'GARNER',
  'MANN',
  'MACK',
  'MOSS',
  'THORNTON',
  'DENNIS',
  'MCGEE',
  'FARMER',
  'DELGADO',
  'AGUILAR',
  'VEGA',
  'GLOVER',
  'MANNING',
  'COHEN',
  'HARMON',
  'RODGERS',
  'ROBBINS',
  'NEWTON',
  'TODD',
  'BLAIR',
  'HIGGINS',
  'INGRAM',
  'REESE',
  'CANNON',
  'STRICKLAND',
  'TOWNSEND',
  'POTTER',
  'GOODWIN',
  'WALTON',
  'ROWE',
  'HAMPTON',
  'ORTEGA',
  'PATTON',
  'SWANSON',
  'JOSEPH',
  'FRANCIS',
  'GOODMAN',
  'MALDONADO',
  'YATES',
  'BECKER',
  'ERICKSON',
  'HODGES',
  'RIOS',
  'CONNER',
  'ADKINS',
  'WEBSTER',
  'NORMAN',
  'MALONE',
  'HAMMOND',
  'FLOWERS',
  'COBB',
  'MOODY',
  'QUINN',
  'BLAKE',
  'MAXWELL',
  'POPE',
  'FLOYD',
  'OSBORNE',
  'PAUL',
  'MCCARTHY',
  'GUERRERO',
  'LINDSEY',
  'ESTRADA',
  'SANDOVAL',
  'GIBBS',
  'TYLER',
  'GROSS',
  'FITZGERALD',
  'STOKES',
  'DOYLE',
  'SHERMAN',
  'SAUNDERS',
  'WISE',
  'COLON',
  'GILL',
  'ALVARADO',
  'GREER',
  'PADILLA',
  'SIMON',
  'WATERS',
  'NUNEZ',
  'BALLARD',
  'SCHWARTZ',
  'MCBRIDE',
  'HOUSTON',
  'CHRISTENSEN',
  'KLEIN',
  'PRATT',
  'BRIGGS',
  'PARSONS',
  'MCLAUGHLIN',
  'ZIMMERMAN',
  'FRENCH',
  'BUCHANAN',
  'MORAN',
  'COPELAND',
  'ROY',
  'PITTMAN',
  'BRADY',
  'MCCORMICK',
  'HOLLOWAY',
  'BROCK',
  'POOLE',
  'FRANK',
  'LOGAN',
  'OWEN',
  'BASS',
  'MARSH',
  'DRAKE',
  'WONG',
  'JEFFERSON',
  'PARK',
  'MORTON',
  'ABBOTT',
  'SPARKS',
  'PATRICK',
  'NORTON',
  'HUFF',
  'CLAYTON',
  'MASSEY',
  'LLOYD',
  'FIGUEROA',
  'CARSON',
  'BOWERS',
  'ROBERSON',
  'BARTON',
  'TRAN',
  'LAMB',
  'HARRINGTON',
  'CASEY',
  'BOONE',
  'CORTEZ',
  'CLARKE',
  'MATHIS',
  'SINGLETON',
  'WILKINS',
  'CAIN',
  'BRYAN',
  'UNDERWOOD',
  'HOGAN',
  'MCKENZIE',
  'COLLIER',
  'LUNA',
  'PHELPS',
  'MCGUIRE',
  'ALLISON',
  'BRIDGES',
  'WILKERSON',
  'NASH',
  'SUMMERS',
  'ATKINS',
];
